# Generated by Django 4.2.5 on 2023-10-27 21:17

from django.db import migrations, models
import ifoodApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, validators=[ifoodApp.validators.validate_even]),
        ),
    ]
