# Generated by Django 4.2.5 on 2023-10-27 22:09

from django.db import migrations, models
import ifoodApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=40, validators=[ifoodApp.validators.validate_even]),
        ),
    ]
