# Generated by Django 4.2.5 on 2023-11-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0010_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifoodApp.endereco'),
        ),
    ]
