# Generated by Django 4.2 on 2023-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0012_produto_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
