# Generated by Django 4.2.5 on 2023-11-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0014_alter_endereco_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(null=True)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifoodApp.user')),
                ('pedidos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifoodApp.produto')),
            ],
        ),
    ]
