# Generated by Django 4.2.5 on 2023-11-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0015_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='cart',
            name='pedidos',
            field=models.ManyToManyField(to='ifoodApp.produto'),
        ),
    ]
