# Generated by Django 4.2.5 on 2023-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0016_remove_cart_pedidos_cart_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessionId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
