# Generated by Django 4.2.5 on 2023-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0017_user_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
