# Generated by Django 4.2.5 on 2023-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0018_cart_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(related_name='produto', to='ifoodApp.produto'),
        ),
    ]
