# Generated by Django 4.2.5 on 2023-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0019_alter_pedido_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pedidos',
            field=models.ManyToManyField(related_name='pedido', to='ifoodApp.produto'),
        ),
    ]
