# Generated by Django 4.2.5 on 2023-12-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0020_alter_cart_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pedidos',
            new_name='produto',
        ),
    ]
