# Generated by Django 4.2.5 on 2023-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0021_rename_pedidos_cart_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantidade',
            field=models.ManyToManyField(to='ifoodApp.produto'),
        ),
    ]
