# Generated by Django 4.2.5 on 2023-12-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0022_remove_pedido_produto_remove_cart_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='Quantidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifoodApp.produto')),
            ],
        ),
    ]
