# Generated by Django 4.2.5 on 2023-12-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0024_quantidades_carrinho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantidades',
            new_name='Info',
        ),
    ]
