# Generated by Django 4.2.5 on 2023-12-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0026_remove_info_carrinho_info_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='produto',
        ),
    ]
