# Generated by Django 4.2.5 on 2023-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0028_alter_info_quantidade_alter_pedido_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='preco_unidade',
            field=models.FloatField(null=True),
        ),
    ]
