# Generated by Django 4.2.5 on 2024-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0030_rename_preco_unidade_info_total_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='total_q',
            field=models.IntegerField(null=True),
        ),
    ]
