# Generated by Django 4.2.5 on 2024-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0031_info_total_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='total_q',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_q',
            field=models.IntegerField(null=True),
        ),
    ]
