# Generated by Django 4.2.5 on 2024-04-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoodApp', '0032_remove_info_total_q_cart_total_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_q',
        ),
    ]
